dist: xenial
language: java
sudo: false
jdk: openjdk8
before_install:
  - chmod +x mvnw
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marcotancredo_bookstoremanager_course
cache:
  directories:
    - $HOME/.m2
