dist: xenial
language: java
sudo: false
jdk: openjdk8
before_install:
  - chmod +x mvnw
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2
